spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/minimalest?serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: create

auth:
  jwt:
    issuer: minimalest.kr
    secret-key: 1234567890abcdefghijk!@#$%^&*()_+
    access-validity-in-seconds: 3600 # 1시간
    refresh-validity-in-seconds: 604800
